version: '2'
services:
 neo4j:
  image: neo4j:latest
  environment:
   - NEO4J_HEAP_MEMORY=2048 # configure the heap memory
   - NEO4J_CACHE_MEMORY=1G # configure the cache memory
  ports:
    - "7474:7474"
    - "7687:7687"
  environment:
    NEO4J_AUTH: "none"
